name: elite_orm
description: A simple and easy-to-use ORM built with sqflite in mind.  It
  provides an object relational mapping without the need to write any
  database code.
version: 1.0.7
homepage: https://github.com/ocielliottc/elite_orm

environment:
  sdk: '>=2.18.5 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  collection: any
